version: '3'
services:
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - .env
    networks:
      - db_nw
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  flaskapp:
    image: tagger-server:latest
    env_file:
      - .env
    networks:
      - db_nw
      - web_nw
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: "nginx:latest"
    ports:
      - "8080:80"
    networks:
      - web_nw
      - clproxy_nw
    depends_on:
      - flaskapp
  clientapp:
    image: tagger-client:latest
    ports:
      - "8081:5000"
    env_file:
      - .env
    networks:
      - clproxy_nw
    depends_on:
      - nginx
networks:
  # connects server with db
  db_nw:
    driver: bridge
  # connects server with server proxy  
  web_nw:
    driver: bridge
  # connects client with api proxy 
  clproxy_nw:
    driver: bridge
volumes:
  dbdata:
